import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";

import { AiBadge, PageHeader, SectionCard } from "@/components/cubiq/primitives";
import { Checkbox } from "@/components/ui/checkbox";
import { mockRecordings, mockSummaries, mockTasks } from "@/lib/cubiq/mock-data";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/ai-insights")({
  head: () => ({
    meta: [
      { title: "AI Insights — CUBIQ" },
      { name: "description", content: "Meeting summaries, key points and action items generated by AI." },
      { property: "og:title", content: "AI Insights — CUBIQ" },
      { property: "og:description", content: "Meeting summaries, key points and action items generated by AI." },
    ],
  }),
  component: InsightsPage,
});

const priorityStyle = {
  high: "bg-danger-soft text-destructive",
  medium: "bg-warning-soft text-warning-foreground",
  low: "bg-muted text-muted-foreground",
} as const;

function InsightsPage() {
  const [tasks, setTasks] = useState(mockTasks);
  const titleOf = (id: string) => mockRecordings.find((r) => r.id === id)?.title ?? "Meeting";
  return (
    <>
      <PageHeader title="AI Insights" description="Summaries and tasks pulled from your meetings." action={<AiBadge />} />
      <div className="grid gap-6 lg:grid-cols-[1.3fr_1fr]">
        <div className="flex flex-col gap-4">
          {mockSummaries.map((s) => (
            <SectionCard key={s.id} title={titleOf(s.recordingId)}>
              <p className="text-sm text-foreground">{s.summary}</p>
              <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                {s.keyPoints.map((k) => (
                  <li key={k}>{k}</li>
                ))}
              </ul>
              <div className="mt-3 flex flex-wrap gap-1.5">
                {s.topics.map((t) => (
                  <span key={t} className="rounded-full bg-secondary px-2.5 py-0.5 text-xs text-secondary-foreground">
                    {t}
                  </span>
                ))}
              </div>
            </SectionCard>
          ))}
        </div>
        <SectionCard title="Action items">
          <ul className="flex flex-col gap-2">
            {tasks.map((t) => (
              <li key={t.id} className="flex items-start gap-3 rounded-lg border border-border p-3">
                <Checkbox
                  checked={t.status === "done"}
                  onCheckedChange={(v) =>
                    setTasks((prev) => prev.map((x) => (x.id === t.id ? { ...x, status: v ? "done" : "open" } : x)))
                  }
                  aria-label={t.title}
                />
                <div className="flex-1">
                  <p className={cn("text-sm text-foreground", t.status === "done" && "line-through text-muted-foreground")}>
                    {t.title}
                  </p>
                  <p className="text-xs text-muted-foreground">{titleOf(t.sourceRecordingId)}</p>
                </div>
                <span className={cn("rounded-full px-2 py-0.5 text-[0.6875rem] font-semibold capitalize", priorityStyle[t.priority])}>
                  {t.priority}
                </span>
              </li>
            ))}
          </ul>
        </SectionCard>
      </div>
    </>
  );
}
