/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as ProductivityRouteImport } from './routes/productivity'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TranscriptsRouteImport } from './routes/transcripts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductivityRoute = ProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/focus': typeof FocusRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/productivity': typeof ProductivityRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transcripts': typeof TranscriptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/focus': typeof FocusRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/productivity': typeof ProductivityRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transcripts': typeof TranscriptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/focus': typeof FocusRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/productivity': typeof ProductivityRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transcripts': typeof TranscriptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/dashboard'
    | '/device'
    | '/focus'
    | '/login'
    | '/meetings'
    | '/productivity'
    | '/recordings'
    | '/settings'
    | '/signup'
    | '/transcripts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/dashboard'
    | '/device'
    | '/focus'
    | '/login'
    | '/meetings'
    | '/productivity'
    | '/recordings'
    | '/settings'
    | '/signup'
    | '/transcripts'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/dashboard'
    | '/device'
    | '/focus'
    | '/login'
    | '/meetings'
    | '/productivity'
    | '/recordings'
    | '/settings'
    | '/signup'
    | '/transcripts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  DashboardRoute: typeof DashboardRoute
  DeviceRoute: typeof DeviceRoute
  FocusRoute: typeof FocusRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  ProductivityRoute: typeof ProductivityRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TranscriptsRoute: typeof TranscriptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  DashboardRoute: DashboardRoute,
  DeviceRoute: DeviceRoute,
  FocusRoute: FocusRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  ProductivityRoute: ProductivityRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TranscriptsRoute: TranscriptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
